In [1]:
import numpy as np
print(np.__version__)


1.26.4


In [2]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [6]:
import numpy as np
a = np.array([1,0,0,0])
print("Original array:")
print(a)
print(np.any(a))
a = np.array([0,0,0,0])
print("Original array:")
print(a)

print(np.any(a))

Original array:
[1 0 0 0]
True
Original array:
[0 0 0 0]
False


In [8]:
import numpy as np
array=np.array([1,-2,np.inf,-np.inf,0,3.5])
result_pos_inf=np.isposinf(array)
result_neg_inf=np.isneginf(array)
print("Original array:")
print(array)
print("Positive infinity:",result_pos_inf)
print("Negative infinity:",result_neg_inf)

Original array:
[ 1.  -2.   inf -inf  0.   3.5]
Positive infinity: [False False  True False False False]
Negative infinity: [False False False  True False False]


In [16]:
#test element wise for NaN of a given array
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test element-wise for NaN:")
print(np.isnan(a))


Original array
[ 1.  0. nan inf]
Test element-wise for NaN:
[False False  True False]


In [12]:
import numpy as np
array=np.arange(30,71)
print("Array of the integers from 30 to 70:")
print(array)

Array of the integers from 30 to 70:
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [14]:
import numpy as np
array=np.arange(30,71,2)
print("Array of the integers from 30 to 70:")
print(array)

Array of the integers from 30 to 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [15]:
import numpy as np
a = np.identity(3)
print('3x3 matrix:')
print(a)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [29]:
import numpy as np
arr1 = np.array([[1,2,3,4],[0,1,3,4],[90,91,93,94],[5,0,3,2]])
print(arr1[::-1])

[[ 5  0  3  2]
 [90 91 93 94]
 [ 0  1  3  4]
 [ 1  2  3  4]]


In [30]:
import numpy as np
arr1 = np.array([[1,2,3,4],[0,1,3,4],[90,91,93,94],[5,0,3,2]])
print(np.transpose(arr1))

[[ 1  0 90  5]
 [ 2  1 91  0]
 [ 3  3 93  3]
 [ 4  4 94  2]]


In [43]:
import numpy as np
arr1 = np.array([[1,2,3,4],[0,1,3,4],[90,91,93,94],[5,0,3,2]])


new_arr1 = arr1[:,[3,2,1,0]]
print(new_arr1)

[[ 4  3  2  1]
 [ 4  3  1  0]
 [94 93 91 90]
 [ 2  3  0  5]]
